spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.9/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.9
    port: 6379
server:
   context-path: /sell


wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 4d2e0f07dec34904fc8ec1000284f2ff

  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e

  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6

  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://runhu.nat100.top/sell/pay/notify

  tomplateId:
    orderStatus: uiuhjnknkn

projectUrl:
  wechatMpAuthorize: http://runhu.nat100.top
  wechatOpenAuthorize: http://runhu.nat100.top
  sell: http://runhu.nat100.top

#mybatis查看sql语句#
logging:
  level:
     com.imooc.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml